{{- if and .Values.azure.applicationId .Values.azure.applicationSecret .Values.azure.tenantId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  azure.application.id: {{ .Values.azure.applicationId }}
  azure.application.secret: {{ .Values.azure.applicationSecret }}
  azure.tenant.id: {{ .Values.azure.tenantId }}
{{- end}}